[local]
localhost   

[catalogue]
catalogue-dev.rk1214.in

[mongodb]
mongodb-dev.rk1214.in

[frontend]
frontend-dev.rk1214.in
 
[redis]
redis-dev.rk1214.in

[user]
user-dev.rk1214.in

[cart]
cart-dev.rk1214.in

[mysql]
mysql-dev.rk1214.in

[shipping]
shipping-dev.rk1214.in

[rabbitmq]
rabbitmq-dev.rk1214.in

[payment]
payment-dev.rk1214.in

[dispatch]
dispatch-dev.rk1214.in


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
mysql_host=mysql-dev.rk1214.in
mysql_root_password=RoboShop@1